Volume_Distributions:
  Blocks: [30, 33, 37]     # length of Cycle becomes num of training blocks in cycle; this order is never shuffled
  Weeks: [17, 22, 28, 33] # length of Block becomes num of training weeks per block

Weight_rounding_factor: 5

Results:
  Directory: data
  Filename: schedule.csv

Lifts:
  Squat:
    Max: 450
    Blocks:
      Volume: 300
    Weekly Distribution: [15, 20, 30, 35] # length of Week becomes num of training days per week
  Bench:
    Max: 340
    Blocks:
      Volume: 450
    Weekly Distribution: [15, 20, 30, 35] # length of Week becomes num of training days per week
  Deadlift:
    Max: 550
    Blocks:
      Volume: 150
    Weekly Distribution: [26, 33, 41] # length of Week becomes num of training days per week
  Press:
    Max: 180
    Blocks:
      Volume: 450
    Weekly Distribution: [15, 20, 30, 35] # length of Week becomes num of training days per week
  Row:
    Max: 225
    Blocks:
      Volume: 450
    Weekly Distribution: [15, 20, 30, 35] # length of Week becomes num of training days per week
